export const genres = {
    Genre: 'genre',
    Action: 'action',
    'Adult & Erotic': 'adult-erotic',
    Adventure: 'adventure',
    'Ancient Literature': 'ancient-literature',
    'Animals & Pets': 'animals-pets',
    'Art & Culture': 'art-culture',
    Biographies: 'biographies',
    Business: 'business',
    Children: 'children',
    'Computer & IT': 'computer-IT',
    Cookbooks: 'cookbooks',
    'Crime & Thriller': 'crime-thriller',
    'Engineering & Technology': 'engineering-technology',
    Environment: 'environment',
    Fantasy: 'fantasy',
    Family: 'family',
    Geography: 'geography',
    History: 'history',
    Horror: 'horror',
    'Hobbies & Lifestyle': 'hobbies-lifestyle',
    Management: 'management',
    Motivation: 'motivation',
    Mystery: 'mystery',
    Mythology: 'mythology',
    Paranormal: 'paranormal',
    Philosophy: 'philosophy',
    Physiology: 'physiology',
    'Religious & Spiritual': 'religious-spiritual',
    Romance: 'romance',
    Sports: 'sports',
    Travel: 'travel',
    Western: 'western',
}

export const language = {
    Language: 'language',
    Bulgarian: 'bulgarian',
    English: 'english',
    French: 'french',
    German: 'german',
    Italian: 'italian',
    Russian: 'russian',
    Spanish: 'spanish',
    Other: 'other'
}


export const bookFormKeys = {
    Title: 'title',
    Author: 'author',
    Genre: 'genre',
    Image: 'image',
    Description: 'description',
    Price: 'price',
    Cover: 'cover',
    'With Cause': 'withCause',
    'Cause URL': 'causeURL',
    Condition: 'condition',
    Language: 'language',
    'Book Location': 'bookLocation',
};